## template: jinja
#cloud-config
ssh_pwauth: true

users:
  - default
  - name: rdma
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

chpasswd:
  expire: false
  users:
    - name: root
      password: linux
      type: text
    - name: rdma
      password: rdma
      type: text

packages:
  - kernel-modules-{{v1.kernel_release}}
  - libfabric
  # RDMA benchmarking utilities
  - qperf
  - libibverbs-utils
  - librdmacm-utils
  - perftest

write_files:
- content: |
    * hard memlock unlimited
    * soft memlock unlimited
    * hard stack 1024000
    * soft stack 1024000
    * hard nofile 1024000
    * soft nofile 1024000
  path: /etc/security/limits.d/99-rdma.conf

# Most of this config actually needs to happen on each boot
bootcmd:
  - ip link set dev eth0 addrgenmode eui64
  - ip link set dev eth0 down
  - ip link set dev eth0 up

runcmd:
  - depmod
  - modprobe rdma_rxe
  - rdma link add rxe0 type rxe netdev eth0
